version: '3.8'

services:
  k-logi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///logistics.db
      - SESSION_SECRET=your-secret-key-here
    volumes:
      - ./instance:/app/instance
      - ./uploaded_gst_bills:/app/uploaded_gst_bills
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 